// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN
#include <iostream>
#include "catch.hpp"
#include "main.hpp"

// ===================== T1 — makevector =====================
TEST_CASE("T1.a makevector size grows correctly", "[T1]")
{
    vector<int> vec;
    makevector(vec, 10);
    REQUIRE(vec.size() == 10);
}
TEST_CASE("T1.b makevector all values in [0, 20)", "[T1]")
{
    vector<int> vec;
    makevector(vec, 20);
    REQUIRE(vec.size() == 20);
    for (int v : vec) {
        REQUIRE(v >= 0);
        REQUIRE(v < 20);
    }
}
TEST_CASE("T1.c makevector appends to existing vector", "[T1]")
{
    vector<int> vec = {99, 99};
    makevector(vec, 5);
    REQUIRE(vec.size() == 7);
    REQUIRE(vec[0] == 99);
    REQUIRE(vec[1] == 99);
    for (size_t i = 2; i < vec.size(); i++) {
        REQUIRE(vec[i] >= 0);
        REQUIRE(vec[i] < 20);
    }
}

// ===================== T2 — sortEvenNumbers: odds in place, evens sorted =====================
TEST_CASE("T2.a sortEvenNumbers fixed input", "[T2]")
{
    vector<int> vec = {6, 7, 0, 4, 5, 2, 10, 1, 8, 2};
    vector<int> before = vec;
    sortEvenNumbers(vec);
    REQUIRE(vec.size() == before.size());
    for (size_t i = 0; i < before.size(); i++)
        if (before[i] % 2 != 0) REQUIRE(vec[i] == before[i]);
    int prev = -1;
    for (int v : vec)
        if (v % 2 == 0) {
            REQUIRE(v >= prev);
            prev = v;
        }
}
TEST_CASE("T2.b sortEvenNumbers all evens", "[T2]")
{
    vector<int> vec = {8, 2, 6, 4, 10, 0};
    sortEvenNumbers(vec);
    REQUIRE(vec[0] == 0);
    REQUIRE(vec[1] == 2);
    REQUIRE(vec[2] == 4);
    REQUIRE(vec[3] == 6);
    REQUIRE(vec[4] == 8);
    REQUIRE(vec[5] == 10);
}
TEST_CASE("T2.c sortEvenNumbers all odds — unchanged", "[T2]")
{
    vector<int> vec = {7, 5, 9, 3, 1};
    vector<int> before = vec;
    sortEvenNumbers(vec);
    REQUIRE(vec == before);
}
TEST_CASE("T2.d sortEvenNumbers on random vector — invariants", "[T2]")
{
    vector<int> vec;
    makevector(vec, 30);
    vector<int> before = vec;
    sortEvenNumbers(vec);
    REQUIRE(vec.size() == before.size());
    for (size_t i = 0; i < before.size(); i++)
        if (before[i] % 2 != 0) REQUIRE(vec[i] == before[i]);
    int prev = -1;
    for (int v : vec)
        if (v % 2 == 0) {
            REQUIRE(v >= prev);
            prev = v;
        }
}

// ===================== T3 — insertEvenNumber =====================
TEST_CASE("T3.a insertEvenNumber into sorted-even vector preserves invariant", "[T3]")
{
    vector<int> vec = {7, 5, 0, 2, 4, 3, 6, 1};
    size_t before_size = vec.size();
    int idx = insertEvenNumber(vec, 8);
    REQUIRE(vec.size() == before_size + 1);
    REQUIRE(vec[idx] == 8);
    int prev = -1;
    for (int v : vec)
        if (v % 2 == 0) {
            REQUIRE(v >= prev);
            prev = v;
        }
}
TEST_CASE("T3.b insertEvenNumber middle insertion", "[T3]")
{
    vector<int> vec = {0, 7, 2, 3, 6, 5};
    int idx = insertEvenNumber(vec, 4);
    REQUIRE(vec[idx] == 4);
    int prev = -1;
    for (int v : vec)
        if (v % 2 == 0) {
            REQUIRE(v >= prev);
            prev = v;
        }
    REQUIRE(find(vec.begin(), vec.end(), 7) != vec.end());
    REQUIRE(find(vec.begin(), vec.end(), 3) != vec.end());
    REQUIRE(find(vec.begin(), vec.end(), 5) != vec.end());
}
TEST_CASE("T3.c insertEvenNumber when no evens — appends at end", "[T3]")
{
    vector<int> vec = {1, 3, 5, 7};
    int idx = insertEvenNumber(vec, 2);
    REQUIRE(idx == 4);
    REQUIRE(vec.back() == 2);
    REQUIRE(vec.size() == 5);
}
TEST_CASE("T3.d insertEvenNumber duplicate even value", "[T3]")
{
    vector<int> vec = {0, 7, 2, 5, 4};
    int idx = insertEvenNumber(vec, 2);
    REQUIRE(vec[idx] == 2);
    REQUIRE(vec.size() == 6);
}

// ===================== T4 — deleteEvenNumber =====================
TEST_CASE("T4.a deleteEvenNumber removes all occurrences", "[T4]")
{
    vector<int> vec = {6, 7, 0, 4, 5, 2, 10, 1, 8, 2};
    int n = deleteEvenNumber(vec, 2);
    REQUIRE(n == 2);
    REQUIRE(find(vec.begin(), vec.end(), 2) == vec.end());
    REQUIRE(vec.size() == 8);
}
TEST_CASE("T4.b deleteEvenNumber no occurrence — returns 0", "[T4]")
{
    vector<int> vec = {1, 3, 5, 7};
    int n = deleteEvenNumber(vec, 4);
    REQUIRE(n == 0);
    REQUIRE(vec.size() == 4);
}
TEST_CASE("T4.c deleteEvenNumber removes all of a unique value", "[T4]")
{
    vector<int> vec = {1, 12, 3, 5, 7};
    int n = deleteEvenNumber(vec, 12);
    REQUIRE(n == 1);
    REQUIRE(find(vec.begin(), vec.end(), 12) == vec.end());
    REQUIRE(vec.size() == 4);
}
TEST_CASE("T4.d deleteEvenNumber removes everything when all match", "[T4]")
{
    vector<int> vec = {6, 6, 6, 6};
    int n = deleteEvenNumber(vec, 6);
    REQUIRE(n == 4);
    REQUIRE(vec.empty());
}
